on:
  push:
    branches:
      - translation

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_PR_TITLE: Update translation
  GH_PR_BODY: This pull request was automatically submitted.
  GH_PR_LABEL: enhancement,help wanted

jobs:
  submit-pr-for-translation:
    if: github.repository_owner == 'ikedas'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Submit PR to update translation
        run: |
          if gh pr list -H $GITHUB_REPOSITORY_OWNER:$GITHUB_REF_NAME \
          --json number | grep 'number'; then
              echo 'PR alreadsy exists.'
          else
            gh pr create -H $GITHUB_REPOSITORY_OWNER:$GITHUB_REF_NAME \
            -t "$GH_PR_TITLE" -b "$GH_PR_BODY" -l "$GH_PR_LABEL"
          fi
